[project]
name = "frontrun-distribute"
description = "A smart contract for transparent and efficient task and milestone distribution on the Stacks blockchain"
authors = ["Your Name <your.email@example.com>"]
telemetry = false
requirements = []

[contracts.distribution_manager]
path = "contracts/distribution-manager.clar"
depends_on = []

[contracts.project_registry]
path = "contracts/project-registry.clar"
depends_on = ["distribution_manager"]

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
